#!/usr/bin/env python3
"""
Velocity Tuner — standalone GUI for tuning per-sector velocity scaling.
Based on UNICORN's vel_scaler_node.py (https://github.com/HMCL-UNIST/unicorn-racing-stack)
Adapted for offline 3D racing line planning pipeline (no ROS dependency).

Reads sector boundaries from sector_friction.yaml (generated by sector_tuner.py)
and provides per-sector velocity scaling sliders.

Generates:
  - sector_velocity.yaml : velocity_scale per sector + global_limit

Usage:
  1. First run sector_tuner.py to define sectors
  2. Then run this tool:
     python track_processing/velocity_tuner.py
"""

import os
import yaml
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button

# ============================================================
# Settings
# ============================================================
params = {
    'track_name': 'experiment_3d_2_3d_smoothed.csv',
    'raceline_name': 'experiment_3d_2_3d_rc_car_timeoptimal.csv',
}

# Paths
dir_path = os.path.dirname(os.path.abspath(__file__))
data_path = os.path.join(dir_path, '..', 'data')
track_path = os.path.join(data_path, 'smoothed_track_data')
raceline_path = os.path.join(data_path, 'global_racing_lines')
sector_config_path = os.path.join(data_path, 'sector_config')


class VelocityTuner:
    """
    Matplotlib GUI for tuning per-sector velocity scaling.
    Adapted from UNICORN's VelocityScaler.

    Shows the track with sector coloring, the original velocity profile,
    and the scaled velocity profile. Per-sector sliders allow real-time tuning.
    """

    def __init__(self, track_csv_path: str, raceline_csv_path: str, sector_yaml_path: str, out_dir: str):
        # Load track data
        self.track = pd.read_csv(track_csv_path)
        self.x = self.track['x_m'].values
        self.y = self.track['y_m'].values
        self.s = self.track['s_m'].values
        self.n_points = len(self.s)

        # Load raceline data (for velocity preview)
        self.has_raceline = False
        if os.path.exists(raceline_csv_path):
            rl = pd.read_csv(raceline_csv_path)
            self.s_rl = rl['s_opt'].values
            self.v_rl = rl['v_opt'].values
            self.has_raceline = True

        # Load sector config from sector_friction.yaml
        with open(sector_yaml_path, 'r') as f:
            self.sector_cfg = yaml.safe_load(f)
        self.n_sectors = self.sector_cfg['n_sectors']

        self.out_dir = out_dir
        os.makedirs(self.out_dir, exist_ok=True)

        # Initialize scaling: global_limit + per-sector
        self.global_limit = 1.0
        self.sector_scales = [1.0] * self.n_sectors

    def _get_sector_bounds(self, i):
        sec = self.sector_cfg[f'Sector{i}']
        return sec['start'], sec['end']

    def _build_velocity_scale_array(self):
        """
        Build per-point velocity scale array with smooth interpolation
        between sectors (adapted from UNICORN's vel_scaler_node.py).
        """
        scale_arr = np.ones(self.n_points)
        # Transition half-length in index points (analogous to UNICORN's hl_change=10m)
        hl_change = max(1, int(10.0 / np.mean(np.diff(self.s)))) if len(self.s) > 1 else 1

        # Assign base scaling per sector
        for i in range(self.n_sectors):
            start, end = self._get_sector_bounds(i)
            sec_scale = min(self.sector_scales[i], self.global_limit)
            scale_arr[start:end + 1] = sec_scale

        # Smooth transitions at sector boundaries (linear interpolation)
        for i in range(self.n_sectors):
            start, end = self._get_sector_bounds(i)
            sec_scale = min(self.sector_scales[i], self.global_limit)

            # Transition at start of sector
            if i > 0:
                prev_scale = min(self.sector_scales[i - 1], self.global_limit)
            else:
                prev_scale = min(self.sector_scales[self.n_sectors - 1], self.global_limit)

            t_start = max(0, start - hl_change)
            t_end = min(self.n_points - 1, start + hl_change)
            if t_end > t_start:
                interp_indices = np.arange(t_start, t_end + 1)
                scale_arr[t_start:t_end + 1] = np.interp(
                    interp_indices,
                    [t_start, t_end],
                    [prev_scale, sec_scale]
                )

        return scale_arr

    def run(self):
        """Launch the velocity tuner GUI."""
        fig = plt.figure(figsize=(14, 9))
        fig.canvas.manager.set_window_title('Velocity Tuner')

        # Layout
        ax_track = fig.add_axes([0.05, 0.45, 0.45, 0.50])
        ax_vel = fig.add_axes([0.55, 0.45, 0.40, 0.50])
        ax_scale_plot = fig.add_axes([0.55, 0.25, 0.40, 0.15])

        # Sliders area: global + per-sector
        n_sliders = 1 + self.n_sectors
        slider_height = 0.025
        slider_gap = 0.005
        slider_base = 0.02
        sliders = []

        # Global limit slider
        ax_gl = fig.add_axes([0.08, slider_base + (n_sliders - 1) * (slider_height + slider_gap), 0.35, slider_height])
        sl_global = Slider(ax_gl, 'Global limit', 0.0, 2.0, valinit=1.0, valstep=0.05)
        sliders.append(sl_global)

        # Per-sector sliders
        sector_sliders = []
        for i in range(self.n_sectors):
            start, end = self._get_sector_bounds(i)
            surface = self.sector_cfg[f'Sector{i}'].get('surface', '?')
            row = n_sliders - 2 - i
            ax_s = fig.add_axes([0.08, slider_base + row * (slider_height + slider_gap), 0.35, slider_height])
            sl = Slider(ax_s, f'S{i} ({surface}) [{start}-{end}]', 0.0, 2.0, valinit=1.0, valstep=0.05)
            sector_sliders.append(sl)
            sliders.append(sl)

        # Save button
        ax_save = fig.add_axes([0.55, 0.02, 0.15, 0.06])
        btn_save = Button(ax_save, 'Save YAML')

        # Reset button
        ax_reset = fig.add_axes([0.75, 0.02, 0.15, 0.06])
        btn_reset = Button(ax_reset, 'Reset All')

        # Initial draw
        self._draw_all(ax_track, ax_vel, ax_scale_plot)

        def on_slider_change(val):
            self.global_limit = sl_global.val
            for i, sl in enumerate(sector_sliders):
                self.sector_scales[i] = sl.val
            self._draw_all(ax_track, ax_vel, ax_scale_plot)
            fig.canvas.draw_idle()

        sl_global.on_changed(on_slider_change)
        for sl in sector_sliders:
            sl.on_changed(on_slider_change)

        def on_save(event):
            self._save_yaml()

        btn_save.on_clicked(on_save)

        def on_reset(event):
            sl_global.set_val(1.0)
            for sl in sector_sliders:
                sl.set_val(1.0)

        btn_reset.on_clicked(on_reset)

        plt.show()

    def _draw_all(self, ax_track, ax_vel, ax_scale):
        scale_arr = self._build_velocity_scale_array()

        # --- Track plot with sector colors ---
        ax_track.cla()
        ax_track.plot(self.x, self.y, 'k-', linewidth=0.5)
        ax_track.grid(True, alpha=0.3)
        ax_track.set_aspect('equal', 'datalim')
        ax_track.set_xlabel('x [m]')
        ax_track.set_ylabel('y [m]')
        ax_track.set_title('Track — sector velocity scaling')

        colors = plt.cm.tab10(np.linspace(0, 1, max(self.n_sectors, 1)))
        for i in range(self.n_sectors):
            start, end = self._get_sector_bounds(i)
            surface = self.sector_cfg[f'Sector{i}'].get('surface', '?')
            sec_scale = min(self.sector_scales[i], self.global_limit)
            ax_track.plot(self.x[start:end + 1], self.y[start:end + 1],
                          color=colors[i], linewidth=3, alpha=0.6,
                          label=f'S{i}: {surface} (v={sec_scale:.2f})')
        ax_track.legend(fontsize=7, loc='best')

        # --- Velocity profile ---
        ax_vel.cla()
        ax_vel.set_title('Velocity Profile')
        ax_vel.set_xlabel('s [m]')
        ax_vel.set_ylabel('V [m/s]')
        ax_vel.grid(True, alpha=0.3)

        if self.has_raceline:
            ax_vel.plot(self.s_rl, self.v_rl, 'k--', linewidth=0.8, alpha=0.5, label='original')
            # Map scale_arr (track points) to raceline points via interpolation
            scale_at_rl = np.interp(self.s_rl, self.s, scale_arr)
            v_scaled = self.v_rl * scale_at_rl
            ax_vel.fill_between(self.s_rl, v_scaled, alpha=0.3, color='green')
            ax_vel.plot(self.s_rl, v_scaled, color='green', linewidth=1.2, label='scaled')
            ax_vel.set_xlim([self.s_rl[0], self.s_rl[-1]])
            ax_vel.set_ylim(bottom=0)
            ax_vel.legend(fontsize=8)
        else:
            ax_vel.text(0.5, 0.5, 'No raceline CSV found\n(preview unavailable)',
                        transform=ax_vel.transAxes, ha='center', va='center', fontsize=10)

        # --- Scale profile ---
        ax_scale.cla()
        ax_scale.set_title('Velocity scale factor', fontsize=9)
        ax_scale.plot(self.s, scale_arr, 'b-', linewidth=1.2)
        ax_scale.set_xlabel('s [m]')
        ax_scale.set_ylabel('scale')
        ax_scale.set_ylim([0, 2.1])
        ax_scale.set_xlim([self.s[0], self.s[-1]])
        ax_scale.grid(True, alpha=0.3)
        ax_scale.axhline(y=1.0, color='k', linewidth=0.5, linestyle='--')

    def _save_yaml(self):
        """Save sector_velocity.yaml."""
        velocity_dict = {
            'global_limit': float(self.global_limit),
            'n_sectors': self.n_sectors,
        }
        for i in range(self.n_sectors):
            start, end = self._get_sector_bounds(i)
            velocity_dict[f'Sector{i}'] = {
                'start': int(start),
                'end': int(end),
                'velocity_scale': float(min(self.sector_scales[i], self.global_limit)),
            }

        velocity_path = os.path.join(self.out_dir, 'sector_velocity.yaml')
        with open(velocity_path, 'w') as f:
            yaml.dump(velocity_dict, f, sort_keys=False, default_flow_style=False)
        print(f'Saved: {velocity_path}')

        for i in range(self.n_sectors):
            start, end = self._get_sector_bounds(i)
            print(f'  Sector{i}: [{start}->{end}] velocity_scale={velocity_dict[f"Sector{i}"]["velocity_scale"]:.2f}')


if __name__ == '__main__':
    track_csv = os.path.join(track_path, params['track_name'])
    raceline_csv = os.path.join(raceline_path, params['raceline_name'])
    sector_yaml = os.path.join(sector_config_path, 'sector_friction.yaml')

    if not os.path.exists(sector_yaml):
        print(f'ERROR: {sector_yaml} not found.')
        print('Run sector_tuner.py first to define sectors.')
        exit(1)

    tuner = VelocityTuner(
        track_csv_path=track_csv,
        raceline_csv_path=raceline_csv,
        sector_yaml_path=sector_yaml,
        out_dir=sector_config_path,
    )
    tuner.run()
